# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91bcea0cebbaa9f931ba16eb9a7a9171b61b783137cb588cd549c72f0d8b2a0adfb3b393b51377c368ae18a16d13a6bd3c04175406d5ceda441092e25a18d875
  PUBLISHABLE_KEY: pk_test_bQawjwGIcWIWv9OoU9Drg0KS
  SECRET_KEY: pk_test_bQawjwGIcWIWv9OoU9Drg0KS
test:
  secret_key_base: e0ed1e4fa44014e1f8045c663f1d3d9ec27d9eb253c7264f50ae4df598d72070a00a839bcac1c6c8443a5772399a6dd7cdd276193dddb16e4bfe033328734092

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  mailer_user_name: <%= ENV["MAILER_USER_NAME"] %>
  mailer_password: <%= ENV["MAILER_PASSWORD"] %>
